// Shared module identities for the conversation replay and full system map.
window.FinanceModules = [
      { id: "api", seq: "01", title: "API 入口", type: "FASTAPI / SSE", zone: "surface", role: "主路径入口", source: "api/app.py", x: 70, y: 303, w: 110, h: 52, copy: "接收用户请求并建立运行上下文；执行过程中的关键状态通过事件流返回前端。" },
      { id: "response", seq: "02", title: "响应规划", type: "RESPONSE PLAN", zone: "core", role: "意图与响应路由", source: "chat/response_plan.py", x: 285, y: 300, w: 130, h: 58, kind: "core", copy: "先判断请求是普通对话、帮助、澄清还是需要数据读取的分析任务。" },
      { id: "validation", seq: "03", title: "动作校验", type: "TOOL DECISION", zone: "core", role: "能力边界校验", source: "chat/tool_decision.py", x: 465, y: 300, w: 130, h: 58, kind: "core", copy: "检查动作是否属于系统允许的技能与操作；不需要读取数据的请求可以在这里直接回复。" },
      { id: "analysis", seq: "04", title: "Schema 与规划", type: "SCHEMA / METHOD", zone: "core", role: "按需展开与方法生成", source: "graph/runtime.py · metadata/schema_selector.py", x: 645, y: 300, w: 130, h: 58, kind: "core", copy: "此节点合并展示：后端检索候选表、模型选择表、系统展开字段与关系，随后生成分析计划和方法。敏感字段在展开后剔除；规划校验失败后回到 Schema 检索，含首轮最多 3 次。" },
      { id: "review-node", seq: "05", title: "方法校验", type: "METHOD / DRY RUN", zone: "review", role: "校验与模拟试运行", source: "harness/method_validator.py · graph/runtime.py", x: 830, y: 300, w: 110, h: 58, copy: "检查表、字段、关系、参数、只读策略与语义，并进行模拟试运行。失败时带结构化错误重新检索 Schema 和规划，超过次数后拒绝该方法。" },
      { id: "approval", seq: "06", title: "用户确认", type: "APPROVAL GATE", zone: "review", role: "方法与范围确认", source: "api/app.py · graph/runtime.py", x: 970, y: 300, w: 110, h: 58, copy: "方法卡展示 SQL 与读取范围，用户确认后进入执行。用户主动修订方法后需再次确认；执行失败后自动修复的分支目前会重新校验，但没有再次确认停点。" },
      { id: "sandbox", seq: "07", title: "本地执行器", type: "PROVIDER / RUNNER", zone: "execution", role: "开发执行实现", source: "sandbox/local_provider.py · sandbox/runtime.py", x: 930, y: 530, w: 130, h: 55, kind: "support", copy: "默认 LocalProcessSandboxProvider 将方法交给 RunnerRegistry 执行。它是开发实现，不提供生产强隔离保证；Firecracker Provider 是待接入方案。" },
      { id: "source", seq: "08", title: "模拟数据执行", type: "MOCK / SQL RUNNER", zone: "execution", role: "当前确认路径的数据", source: "sandbox/mock_sandbox.py · sandbox/runners/sql.py", x: 770, y: 610, w: 130, h: 56, kind: "support", copy: "当前确认路径调用 run_simulated_real_execution，输入生成的模拟数据；SQL Runner 使用配置的 PostgreSQL 执行。仓库另有 direct_db 执行器，但它不是这条确认路径的默认实现。" },
      { id: "reply", seq: "09", title: "私有结果解读", type: "RESULT NARRATOR", zone: "surface", role: "面向用户的结果解读", source: "renderer/result_narrator.py", x: 70, y: 595, w: 110, h: 54, copy: "专门的结果解读模型接收执行结果并向用户生成说明。结果与解读保存在私有路径，不写回普通规划对话；是否调用外部模型取决于提供方配置。" },
      { id: "llm", seq: "C1", title: "模型提供方", type: "LLM PROVIDER", zone: "context", role: "规划与解读调用", source: "llm/provider.py", x: 280, y: 110, w: 124, h: 52, kind: "support", copy: "普通规划使用筛选后的 Schema 与安全上下文；结果解读则通过单独调用接收结果数据。两者可以使用同一个配置的模型提供方。" },
      { id: "memory", seq: "C2", title: "记忆上下文", type: "SELECTOR / SUMMARY", zone: "context", role: "相关上下文", source: "memory/selector.py", x: 447, y: 110, w: 124, h: 52, kind: "support", copy: "只选择与当前请求相关的对话摘要、引用和安全上下文，控制注入范围。" },
      { id: "policy", seq: "C3", title: "目录与策略", type: "REGISTRY / POLICY", zone: "context", role: "结构与约束", source: "metadata/table_registry.py · metadata/policy.py", x: 614, y: 110, w: 124, h: 52, kind: "support", copy: "TableRegistry 提供运行时 Schema；后端检索少量表摘要，再按模型选择展开字段与关系。字段策略继续剔除敏感字段。" },
      { id: "result-store", seq: "E1", title: "私有结果存储", type: "PRIVATE RESULT STORE", zone: "evidence", role: "结果与证据", source: "memory/private_result_store.py", x: 515, y: 530, w: 132, h: 48, kind: "support", copy: "保存结果本身、结果引用、内容哈希、方法与授权哈希。私有表示与普通规划上下文分开，并不表示执行结束后删除，也不是加密保证。" },
      { id: "audit", seq: "E2", title: "审计与状态", type: "AUDIT / CHECKPOINT", zone: "evidence", role: "过程证据", source: "audit/audit_logger.py", x: 330, y: 530, w: 132, h: 48, kind: "support", copy: "记录规划、确认、执行、错误与恢复状态，为复核和故障恢复保留轨迹。" }
    ];
